import type { Metadata } from "next";
import { Roboto, Poppins } from 'next/font/google'
import "./globals.css";

const roboto = Roboto({
  weight: ['300', '400', '500', '700', '900'],
  display: 'swap',
  variable: '--font-roboto'
})

const poppins = Poppins({
  weight: ['300', '400', '500', '700', '900'],
  display: 'swap',
  variable: '--font-poppins'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className} ${poppins.className} antialiased`}
      >
        <div>

          <div>
            {children}
          </div>
          
        </div>
      </body>
    </html>
  );
}
